#include <stdio.h>   // For printf, fgets, stdin
#include <stdlib.h>  // For atoi
#include <string.h>  // For strtok


// Declare the triangle function from Triangle.c
void triangle(int a, int b, int c);

// The main function to drive the triangle function for coverage
int main() {
    char buffer[256]; // Max input size
    FILE *input_file;

    // Open the fuzzer_test_suite.txt generated by AFL++
    input_file = fopen("fuzzer_test_suite.txt", "r");
    if (input_file == NULL) {
        perror("Error opening fuzzer_test_suite.txt");
        return 1;
    }

    // Read each line (test case) from the fuzzer_test_suite.txt
    while (fgets(buffer, sizeof(buffer), input_file) != NULL) {
        // Parse the input (expecting three space-separated integers)
        int a, b, c;
        char *token;

        token = strtok(buffer, " \n\r");
        if (token == NULL) continue;
        a = atoi(token);

        token = strtok(NULL, " \n\r");
        if (token == NULL) continue;
        b = atoi(token);

        token = strtok(NULL, " \n\r");
        if (token == NULL) continue;
        c = atoi(token);

        // Call the triangle function with the parsed input
        triangle(a, b, c);
    }

    fclose(input_file);
    return 0;
}
